name: ELF to WPS
on: [push]
jobs:
  convert:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          dkp-pacman -Syyu --noconfirm
          dkp-pacman -S --noconfirm wut

      - name: Ultimate Convert
        run: |
          # 1. Tool finden
          WPS_TOOL=$(find /opt/devkitpro -name "wut-wpsgen" | head -n 1)
          echo "Nutze Tool: $WPS_TOOL"
          
          # 2. Rechte für die ELF erzwingen
          chmod 777 King-Gamepad-vWii.elf
          
          # 3. Umwandlung starten (mit vollem Pfad)
          $WPS_TOOL King-Gamepad-vWii.elf King-Gamepad-vWii.wps
          
          # 4. Prüfen ob Datei da ist
          ls -lh King-Gamepad-vWii.wps
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Fertiges-Plugin
          path: King-Gamepad-vWii.wps
