name: ELF to WPS
on: [push]
jobs:
  convert:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Everything
        run: |
          dkp-pacman -Syyu --noconfirm
          dkp-pacman -S --noconfirm wut

      - name: Find and Convert
        run: |
          # Wir suchen die Datei wut-wpsgen überall und speichern den Pfad
          WPSGEN_PATH=$(find /opt/devkitpro -name "wut-wpsgen" | head -n 1)
          echo "Tool gefunden unter: $WPSGEN_PATH"
          
          # Ausführen mit dem gefundenen Pfad
          $WPSGEN_PATH King-Gamepad-vWii.elf King-Gamepad-vWii.wps
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Fertiges-Plugin
          path: King-Gamepad-vWii.wps
